MODEL:
  NUM_CLASSES: 81
  FCOS_ON: True
INPUT:
  IMAGE_SIZE: 512
DATASETS:
  TRAIN: ("coco_2017_train")
  TEST: ("coco_2017_val")
SOLVER:
  MAX_ITER: 400000
  LR_STEPS: [280000, 360000]
  GAMMA: 0.1
  BATCH_SIZE: 24
  LR: 1e-3
TEST:
  MAX_PER_CLASS: 400
